plugins:
  - prettier
env:
  jest: true
extends:
  - airbnb
  - prettier
  - prettier/react
globals:
  graphql: true
rules:
  # remove <Link/> from anchor-is-valid
  jsx-a11y/anchor-is-valid:
    - error
    - components: []
  react/no-unused-prop-types: off
  no-unused-vars: off
settings:
  import/core-modules: ['react', 'react-helmet']
